name: docker

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - name: JSON to variables
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: 'package.json'
          prefix: 'package'
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: jamescurtisfoxmail/${{ env.package_name }}
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
